spring.application.name=demos_

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d472qe24d50c7397h4sg-a.oregon-postgres.render.com:5432/devptdb
spring.datasource.username=devptdb_user
spring.datasource.password=b92GXMZdbr12Q9u4Jh5rQ97iE4jf75HW

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=8081

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB




